### ISSUE TITLE
REQUEST: Add debug_guild kwarg to load func to remove guild_id from command decorators

### ISSUE THREAD

**Issue by Dworv** [Toricane/better-interactions#5]
`bot.load('interactions.ext.better-interactions', debug_guild=2152534532454)`

this feature would save a lot of time testing commands and would take yet another argument out of the command decorator, possibly removing all args maybe?

**Comment by Toricane** [comment]
I would probably name it `debug_scope` so you could have multiple guilds, will be implemented

**Comment by Toricane** [comment]
Implemented
